#!/bin/bash
if [ ! -d .venv/bin ]; then
  virtualenv .venv
fi
source .venv/bin/activate

if ! [ -x "$(command -v pip-sync)" ]; then
  pip install pip-tools==1.9.0
fi

if [ -n "$DEBUG" ]; then
  echo "Syncing python libs; this will take a moment"

  if git diff --exit-code eregs_libs/regulations-site > /dev/null
  then
    git submodule update eregs_libs/regulations-site
  else
    echo "Warning: Modified version of regulations-site detected"
  fi

  if git diff --exit-code eregs_libs/regulations-core > /dev/null
  then
    git submodule update eregs_libs/regulations-core
  else
    echo "Warning: Modified version of regulations-core detected"
  fi

  # Unfortunately, due to the editable libraries, pip-sync will always have
  # quite a bit of output. Hide it!
  pip-sync requirements_dev.txt > /dev/null
  echo "Done!"
else
  pip-sync requirements.txt
fi


exec "$@"
